Fix error C2440
When I compile, I got 
```
error C2440: '=': cannot convert from 'const wchar_t [175]' to 'LPWSTR'
```

This fixes the problem by using QString.